package Translator_prot.Expressions;

public enum PATTERN_TYPES {
    STR_VAR,
    CHAR_VAR,
    LOOP,
    IF_CONDITION,
    ELSE_CONDITION,
    ELIF_CONDITION,
    TERNARY,
    FUNC_DECL,
    FUNC_CALL,
    VAR_DECL,
    VAR_ASSIGNMENT,
    EMPTY_OPERATOR,
    DEPENDENCY,
    PYTHON_FUNC_DECL,
    PYTHON_FUNC_CALL
}
